cluster.name: CLUSTER-NAME
node.name: ${HOSTNAME}
path.data: DATA-PATH
path.logs: LOG-DIR
network.host: BIND-ADDRESS
http.port: 9200
discovery.seed_hosts: [ SEED_HOSTS ]
cluster.initial_master_nodes: [ SEED_HOSTS ]
gateway.recover_after_nodes: REC-NODES
xpack.ml.enabled: false
xpack.license.self_generated.type: basic
bootstrap.system_call_filter: false

